[package]
name = "dnsbl"
version = "0.1.0"
authors = ["Euan Kemp <euank@euank.com>"]
edition = "2018"

[lib]
name = "dnsbl"
path = "src/lib.rs"

[dependencies]
serde = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0"
clap = "2"
log = "0.4"
env_logger = "0.6"
trust-dns = "0.15.0"

