[package]
name = "dnsbl"
version = "0.1.0"
authors = ["Euan Kemp <euank@euank.com>"]
edition = "2018"
license = "MIT"

[dependencies]
failure = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
trust-dns = "0.15.0"
trust-dns-proto = "0.6.0"
